consul:
  container_name: consul.server
  command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1
  image: consul:latest
  volumes:
    - ./etc/consul.server/config:/consul/config
  ports:
    - "9300:9300"
    - "9500:9500"
    - "9600:9600/udp"
vault:
  container_name: vault.server
  image: vault
  ports:
    - "9200:8200"
  volumes:
    - ./etc/vault.server/config:/vault/config
    - ./etc/vault.server/data:/vault/data
    - ./etc/vault.server/logs:/vault/logs
  environment:
    - SKIP_SETCAP=1
    - VAULT_LOCAL_CONFIG={"disable_mlock":"true","backend":{"consul":{"address":"${LOCAL_IP}:9500","advertise_addr":"http://${LOCAL_IP}","path":"vault/"}},"default_lease_ttl":"168h","max_lease_ttl":"720h","listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}}}
  command: server 
